# Certification Process for Upcoming Expirations

## Libraries Import

In [1]:
import pandas as pd
import numpy as np
from email.message import EmailMessage
import win32com.client as win32
import os

## Get Config

### Getting Sheets of the config file

In [45]:
config_file_path = "../data/Config.xlsx"
df_config = pd.read_excel(config_file_path, sheet_name="Config")
df_data = pd.read_excel(config_file_path, sheet_name="Data")
df_Mail = pd.read_excel(config_file_path, sheet_name="Mail")

### Variables

In [40]:
#Folder path where files are stored
shared_folder = df_config.iloc[0,1]

shared_folder

'C:\\Users\\25004549\\Documents\\02. UiPath Projects\\00. M1\\02. Certification_upcoming_expirations\\notebook\\data'

In [41]:
df_data

               Filename   Sheet
0  Copy of 10.-SMD.xlsm  OP 1 C
1  Copy of 10.-SMD.xlsm  OP 2 C
2  Copy of 10.-SMD.xlsm  OP 3 C
3  Copy of 10.-SMD.xlsm  OP 5 C
4          10.-SMT.xlsm  OP 1 C
5          10.-SMT.xlsm  OP 2 C
6          10.-SMT.xlsm  OP 3 C
7          10.-SMT.xlsm  OP 5 C

In [42]:
df_Mail

,To,CC,CCO
0,gilberto.gaytan@wnc.com.tw,ggaytan_itcj@hotmail.com,bto_pachu15@hotmail.com

## Data Understanding

### Get Data

In [2]:
df_certifications = pd.read_excel('../data/Copy of 10.-SMD.xlsm',sheet_name='OP 1 C')

c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [3]:
df_certifications.sample(5)

,Número,Nombre completo,Nombre puesto,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
343,211044,"Salazar Saucedo, Jesus",Almacenista,NaN,NaN,NaN,NaN,730,1901-12-30 00:00:00,-45404,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,207765,"Garcia Rodriguez, Lidia",Operador 3,NaN,NaN,NaN,NaN,730,1901-12-30 00:00:00,-45404,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,203540,"Ponce Gonzalez, Lilia Maria",Operador 1,237641,"Velazquez Castillejos, Maria Esther",Programacion y PXI SMD,2025-04-17 00:00:00,730,2027-04-17 00:00:00,360,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,201982,"Mata Vargas, Enrique Javier",Supervisor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADJ_1489 Rev C
818,301871,"Ramos Prieto, Sandra Liliana",Accounts Payable/Receivable Specialist Ii,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Transformation

In [46]:
def extract_data(shared_folder,filename, sheet):
    df = pd.read_excel((shared_folder + "\\"+filename), sheet_name=sheet)
    #removiendo columnas y filas no necesarias
    df = df.iloc[10:,3:]

    #Conservando columnas por usar
    df = df.iloc[:, :8]

    #promoviendo primera fila como titulos de columnas
    df.columns = df.iloc[0]
    df = df[1:]

    #removiendo nulos
    df = df.dropna()

    #Obteniendo dias de diferencia entre fecha de expiracion y fecha actual
    df['Dias por expirar'] = (pd.to_datetime(df['FECHA DE RECERTIFICACION']) - pd.to_datetime('today')).dt.days

    #filtrar por dias por expirar menores a 100
    df = df[df['Dias por expirar'] < 100]

    #Removiendo columnas no necesarias
    df = df.drop(columns=['DIAS A VENCER','ALERTA', 'PARAMETRO DE CERTIFICACION'])

    #Dejando columnas fecha solo con formato fecha
    df['FECHA DE RECERTIFICACION'] = pd.to_datetime(df['FECHA DE RECERTIFICACION']).dt.date
    df['FECHA DE CERTIFICACION MM/DD/AAAA'] = pd.to_datetime(df['FECHA DE CERTIFICACION MM/DD/AAAA']).dt.date
    return df

In [47]:
report = []
#Leyyendo los datos de las certificaciones
for row in df_data.itertuples():
    filename = row.Filename 
    sheet = row.Sheet
    
    try:
        df = extract_data(shared_folder, filename, sheet)
        report.append(df)
    except Exception as e:
        print(f"Error al procesar el archivo {filename} y hoja {sheet}: {e}")

df_report = pd.concat(report, ignore_index=True)

c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Error al procesar el archivo Copy of 10.-SMD.xlsm y hoja OP 5 C: Worksheet named 'OP 5 C' not found

c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [48]:
df_report

10,PID,NOMBRE,CERTIFICACION,FECHA DE CERTIFICACION MM/DD/AAAA,FECHA DE RECERTIFICACION,Dias por expirar
0,280178,"Castañon Quintanar, Alicia",Corte de Tablilla (Depanelizado),2024-08-06,2026-08-06,97
1,280178,"Castañon Quintanar, Alicia",Programacion y PXI SMD,2024-08-06,2026-08-06,97
2,203358,"Vazquez Ordaz, Virginia",Programacion y PXI SMD,2024-02-01,2026-01-31,-90
3,202311,"Carrera Rivera, Eugenia",Corte de Tablilla (Depanelizado),2024-02-01,2026-01-31,-90
4,202311,"Carrera Rivera, Eugenia",Programacion y PXI SMD,2024-02-01,2026-01-31,-90
...,...,...,...,...,...,...
78,202259,"Velazquez Delgado, Adriana Ivette",Manejo y uso de maquinas de SMT,2024-03-22,2026-03-22,-40
79,202303,"Hernandez Centeno, Santa Alicia",Manejo y uso de maquinas de SMT,2024-01-31,2026-01-30,-91
80,207799,"Carrillo Ortiz, Elizabeth",Operador Universal,2024-03-22,2024-02-02,-819
81,288284,"Soto Rico, Ivan De Jesus",Manejo y uso de maquinas de SMT,2024-03-22,2026-03-22,-40
82,289658,"Marquez Sierra, Yaslin",Manejo y uso de maquinas de SMT,2023-10-03,2025-10-02,-211

In [31]:
df_report.sample(15)

10,PID,NOMBRE,CERTIFICACION,FECHA DE CERTIFICACION MM/DD/AAAA,FECHA DE RECERTIFICACION,Dias por expirar
7,278988,"Reynoso Rubio, Teresita De Jesus",Programacion y PXI SMD,2024-03-08,2026-03-08,-54
22,228618,"Lopez Mendez, Deyanira",Prueba ICT,2024-02-26,2026-02-25,-65
15,202242,"Ortega Gonzalez, Ma. Del Rosario",Movedor de Materiales,2024-04-19,2026-04-19,-12
34,202242,"Ortega Gonzalez, Ma. Del Rosario",Prueba AOI,2024-05-24,2026-05-24,23
30,202267,"Betancourt Valle, Maribel",Prueba AOI,2024-05-24,2026-05-24,23
2,203358,"Vazquez Ordaz, Virginia",Programacion y PXI SMD,2024-02-01,2026-01-31,-90
4,202311,"Carrera Rivera, Eugenia",Programacion y PXI SMD,2024-02-01,2026-01-31,-90
32,202231,"Mateos Martin, Edmundo",Prueba AOI,2024-05-24,2026-05-24,23
24,289878,"Reyes Antonio, Yesenia",Prueba ICT,2023-12-05,2025-12-04,-148
18,202236,"Hernandez Santos, Alejandrina",Prueba ICT,2024-03-11,2026-03-11,-51
3,202311,"Carrera Rivera, Eugenia",Corte de Tablilla (Depanelizado),2024-02-01,2026-01-31,-90
1,280178,"Castañon Quintanar, Alicia",Programacion y PXI SMD,2024-08-06,2026-08-06,97
6,207755,"Martinez Gallegos, Rodolfo",Corte de Tablilla (Depanelizado),2024-02-01,2026-01-31,-90
14,202043,"Morales Gonzalez, Ma. De Jesus",Soldadura,2024-02-22,2026-02-21,-69
16,202316,"Suarez Palomares, Brenda",Movedor de Materiales,2024-04-19,2026-04-19,-12

## Data Modeling

In [49]:
df_report.to_excel('../reports/Certifications to expiring.xlsx', index=False)
ruta_archivo = os.path.abspath("../reports/Certifications to expiring.xlsx")

In [50]:
sender = "p_m1dmis_rpa01@wnc.com.tw"
receiver = "gilberto.gaytan@wnc.com.tw"
pwd = 'Wnewebmx2026.'

msg  = EmailMessage()
msg['From'] = sender
msg['To'] = receiver   
msg['Subject'] = "Certificaciones por expirar en menos de 100 dias"
msg.set_content("Hola, adjunto el reporte de certificaciones por expirar en menos de 100 dias")

In [51]:

outlook = win32.Dispatch('outlook.application')
mail = outlook.CreateItem(0)
mail.SentOnBehalfOfName = sender
mail.To = receiver
mail.Subject = "Certificaciones por expirar"
mail.Body = "Buen dia, se comparte el reporte de certificaciones por expirar en menos de 100 dias \nFavor de incluir en programa semanal \nSaludos!"
mail.attachments.Add(ruta_archivo)
mail.Send()