# Certification Process for Upcoming Expirations

## Libraries Import

In [2]:
import pandas as pd
import numpy as np
from email.message import EmailMessage
import win32com.client as win32
import os
import numpy as np

## Get Config

### Getting Sheets of the config file

In [3]:
config_file_path = "../data/Config.xlsx"
df_config = pd.read_excel(config_file_path, sheet_name="Config")
df_data = pd.read_excel(config_file_path, sheet_name="Data")
df_Mail = pd.read_excel(config_file_path, sheet_name="Mail")

### Variables

In [4]:
#Folder path where files are stored
shared_folder = df_config.iloc[0,1]

shared_folder

'C:\\Users\\25004549\\Documents\\02. UiPath Projects\\00. M1\\02. Certification_upcoming_expirations\\notebook\\data'

In [5]:
df_data

               Filename   Sheet
0  Copy of 10.-SMD.xlsm  OP 1 C
1  Copy of 10.-SMD.xlsm  OP 2 C
2  Copy of 10.-SMD.xlsm  OP 3 C
3  Copy of 10.-SMD.xlsm  OP 5 C
4          10.-SMT.xlsm  OP 1 C
5          10.-SMT.xlsm  OP 2 C
6          10.-SMT.xlsm  OP 3 C
7          10.-SMT.xlsm  OP 5 C

In [6]:
df_Mail

,To,CC,CCO
0,gilberto.gaytan@wnc.com.tw,ggaytan_itcj@hotmail.com,bto_pachu15@hotmail.com
1,ggaytan.analytics@outlook.com,NaN,NaN

## Data Understanding

### Get Data

In [7]:
df_certifications = pd.read_excel('../data/Copy of 10.-SMD.xlsm',sheet_name='OP 1 C')

c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [8]:
df_certifications.sample(5)

,Número,Nombre completo,Nombre puesto,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
752,301756,"Castro Soriano, Iridiana",Operador 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,207900,"Armenta Gonzalez, Roman",Especialista En Ctrl De Prod,NaN,NaN,NaN,NaN,730,1901-12-30 00:00:00,-45404,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,300339,"Juarez Perez, Martha Anahi",Operador 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,201990,"Soto Contreras, Jose Guerrero",Lider Control Inventarios,202043,"Morales Gonzalez, Ma. De Jesus",Corte de Tablilla (Depanelizado),2024-12-18 00:00:00,730,2026-12-18 00:00:00,240,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,202315,"Garcia Fernandez, Leticia",Operador 2,289652,"Valenzuela Flores, Edgar",Programacion y PXI SMD,2025-12-02 00:00:00,730,2027-12-02 00:00:00,589,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Transformation

In [9]:
def extract_data(shared_folder,filename, sheet):
    df = pd.read_excel((shared_folder + "\\"+filename), sheet_name=sheet)
    #removiendo columnas y filas no necesarias
    df = df.iloc[10:,3:]

    #Conservando columnas por usar
    df = df.iloc[:, :8]

    #promoviendo primera fila como titulos de columnas
    df.columns = df.iloc[0]
    df = df[1:]

    #removiendo nulos
    df = df.dropna()

    #Obteniendo dias de diferencia entre fecha de expiracion y fecha actual
    df['Dias por expirar'] = (pd.to_datetime(df['FECHA DE RECERTIFICACION']) - pd.to_datetime('today')).dt.days

    #filtrar por dias por expirar menores a 100
    df = df[df['Dias por expirar'] < 100]

    #Removiendo columnas no necesarias
    df = df.drop(columns=['DIAS A VENCER','ALERTA', 'PARAMETRO DE CERTIFICACION'])

    #Dejando columnas fecha solo con formato fecha
    df['FECHA DE RECERTIFICACION'] = pd.to_datetime(df['FECHA DE RECERTIFICACION']).dt.date
    df['FECHA DE CERTIFICACION MM/DD/AAAA'] = pd.to_datetime(df['FECHA DE CERTIFICACION MM/DD/AAAA']).dt.date
    return df

In [10]:
report = []
#Leyyendo los datos de las certificaciones
for row in df_data.itertuples():
    filename = row.Filename 
    sheet = row.Sheet
    
    try:
        df = extract_data(shared_folder, filename, sheet)
        report.append(df)
    except Exception as e:
        print(f"Error al procesar el archivo {filename} y hoja {sheet}: {e}")

df_report = pd.concat(report, ignore_index=True)

c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Error al procesar el archivo Copy of 10.-SMD.xlsm y hoja OP 5 C: Worksheet named 'OP 5 C' not found

c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\25004549\Documents\02. UiPath Projects\00. M1\02. Certification_upcoming_expirations\notebook\env\lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [11]:
df_report

10,PID,NOMBRE,CERTIFICACION,FECHA DE CERTIFICACION MM/DD/AAAA,FECHA DE RECERTIFICACION,Dias por expirar
0,280178,"Castañon Quintanar, Alicia",Corte de Tablilla (Depanelizado),2024-08-06,2026-08-06,93
1,280178,"Castañon Quintanar, Alicia",Programacion y PXI SMD,2024-08-06,2026-08-06,93
2,203358,"Vazquez Ordaz, Virginia",Programacion y PXI SMD,2024-02-01,2026-01-31,-94
3,202311,"Carrera Rivera, Eugenia",Corte de Tablilla (Depanelizado),2024-02-01,2026-01-31,-94
4,202311,"Carrera Rivera, Eugenia",Programacion y PXI SMD,2024-02-01,2026-01-31,-94
...,...,...,...,...,...,...
80,202259,"Velazquez Delgado, Adriana Ivette",Manejo y uso de maquinas de SMT,2024-03-22,2026-03-22,-44
81,202303,"Hernandez Centeno, Santa Alicia",Manejo y uso de maquinas de SMT,2024-01-31,2026-01-30,-95
82,207799,"Carrillo Ortiz, Elizabeth",Operador Universal,2024-03-22,2024-02-02,-823
83,288284,"Soto Rico, Ivan De Jesus",Manejo y uso de maquinas de SMT,2024-03-22,2026-03-22,-44
84,289658,"Marquez Sierra, Yaslin",Manejo y uso de maquinas de SMT,2023-10-03,2025-10-02,-215

In [12]:
df_report.sample(15)

10,PID,NOMBRE,CERTIFICACION,FECHA DE CERTIFICACION MM/DD/AAAA,FECHA DE RECERTIFICACION,Dias por expirar
7,278988,"Reynoso Rubio, Teresita De Jesus",Programacion y PXI SMD,2024-03-08,2026-03-08,-58
67,208914,"Quezada Alvarado, Laura Patricia",Prueba ICT,2024-05-24,2026-05-24,19
15,202043,"Morales Gonzalez, Ma. De Jesus",Soldadura,2024-02-22,2026-02-21,-73
12,208510,"Santos Alonso, Patricia",Soldadura,2024-02-21,2026-02-20,-74
44,207799,"Carrillo Ortiz, Elizabeth",Programacion y PXI SMT,2024-08-06,2026-08-06,93
51,202315,"Garcia Fernandez, Leticia",Soldadura,2024-02-21,2026-02-20,-74
10,287333,"Nevarez Olivas, Vanessa Lizeth",Corte de Tablilla (Depanelizado),2024-05-27,2026-05-27,22
41,202236,"Hernandez Santos, Alejandrina",Corte de Tablilla (Depanelizado),2024-04-04,2026-04-04,-31
47,208354,"Padilla Silva, Angelica",Programacion y PXI SMT,2024-02-01,2026-01-31,-94
52,202252,"Candelario Martinez, Flor Maria",Soldadura,2024-02-22,2026-02-21,-73
22,208914,"Quezada Alvarado, Laura Patricia",Prueba AOI,2024-02-26,2026-02-25,-69
36,202316,"Suarez Palomares, Brenda",Prueba ICT,2024-05-24,2026-05-24,19
11,280178,"Castañon Quintanar, Alicia",Soldadura,2024-08-12,2026-08-12,99
33,202231,"Mateos Martin, Edmundo",Prueba AOI,2024-05-24,2026-05-24,19
8,294787,"Garcia Ordoñez, Maria Del Refugio",Programacion y PXI SMD,2024-04-04,2026-04-04,-31

## Data Modeling

In [23]:
df_report.to_excel('../reports/Certifications to expiring.xlsx', index=False)
ruta_archivo = os.path.abspath("../reports/Certifications to expiring.xlsx")

### Config Mail List to send the report

In [32]:
list_to = ";".join(df_Mail["To"].dropna().astype(str))
list_cc = ";".join(df_Mail["CC"].dropna().astype(str))
list_cco = ";".join(df_Mail["CCO"].dropna().astype(str))

In [34]:
list_cc

'ggaytan_itcj@hotmail.com'

In [35]:
sender = "p_m1dmis_rpa01@wnc.com.tw"
receiver = list_to
pwd = 'Wnewebmx2026.'


outlook = win32.Dispatch('outlook.application')
mail = outlook.CreateItem(0)
mail.SentOnBehalfOfName = sender
mail.To = receiver
mail.cc = list_cc
#mail.bcc = list_cco
mail.Subject = "Certificaciones por expirar"
mail.Body = "Buen dia, se comparte el reporte de certificaciones por expirar en menos de 100 dias \nFavor de incluir en programa semanal \nSaludos!"
mail.attachments.Add(ruta_archivo)
mail.Send()


#msg  = EmailMessage()
#msg['From'] = sender
#msg['To'] = list_to   
#msg['Subject'] = "Certificaciones por expirar en menos de 100 dias"
#msg.set_content("Hola, adjunto el reporte de certificaciones por expirar en menos de 100 dias")

In [24]:

outlook = win32.Dispatch('outlook.application')
mail = outlook.CreateItem(0)
mail.SentOnBehalfOfName = sender
mail.To = receiver
mail.cc = list_cc
#mail.bcc = list_cco
mail.Subject = "Certificaciones por expirar"
mail.Body = "Buen dia, se comparte el reporte de certificaciones por expirar en menos de 100 dias \nFavor de incluir en programa semanal \nSaludos!"
mail.attachments.Add(ruta_archivo)
mail.Send()